# Docker Compose configuration

services:
  symbiotic-restaking:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: symbiotic-restaking-service
    restart: unless-stopped
    environment:
      - PRIVATE_KEY=1e91d879daec318b8a5f97fb9b08f9753740196a65c8f9e62fd9e45961eaba8a
      - ETHEREUM_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com
      - CONTRACT_ADDRESS=0x656e79454a277198566412d9bff26f97297633cc
      - RUST_LOG=info
    volumes:
      - ./logs:/app/logs